config/routes.rb
Rails.application.routes.draw do

    get '/signup', to: 'users#new'

    get '/signin', to: 'sessions#new'

    post '/signin', to: 'sessions#create'

    resources :users, only: [ :new, :create, :show ]

    resources :events, only: [ :new, :create, :show, :index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :host, :class_name => "User"
    has_many :invitations
    has_many :invitees, :through => :invitations
    has_many :attendees, :through => :invitations

    scope :upcoming, lambda { where("#{:date} >= ?", Date.today) }
    scope :past, lambda { where("#{:date} < ?", Date.today) }

    default_scope -> { order(:date) }
end

app/models/invitation.rb
class Invitation < ApplicationRecord
    belongs_to :event
    belongs_to :invitee, :class_name => "User"
    belongs_to :attendee, :class_name => "User"
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :hosting_events, :foreign_key => "host_id", :class_name => "Event"
    has_many :invitations, :foreign_key => "invitee_id"
    has_many :invited_events, :foreign_key => "invitee_id", :through => :invitations, :source => "event"
    has_many :attended_events, :foreign_key => "attendee_id", :through => :invitations, :source => "event"

    def User.digest(token)
        Digest::SHA1.hexdigest(token.to_s)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :logged_in_user, only: [:create]

  def new
      @event = Event.new
  end

  def create
      @event = current_user.hosting_events.build(event_params)
      if @event.save
          flash[:success] = "Event created!"
      else
        render 'new'
      end
  end

  def show
      @event = Event.find(params[:id])
      @attendees = @event.attendees
  end

  def index
      @upcoming_events = Event.upcoming
      @past_events = Event.past
  end

  private

    def logged_in_user
        redirect_to '/signin' unless signed_in?
    end

    def event_params
        params.require(:event).permit(:description)
    end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController

    def new
        @invitation = Invitation.new
    end

    def create

    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        user = User.find_by(username: params[:session][:username])
        if user
            signin user
            redirect_to user
        else
            flash.now[:warning] = "Could not find username."
            render 'new'
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def new
        @user = User.new
    end

    def create
       @user = User.new
       @user.username = user_params[:username] 
       @user.password_digest = User.digest(user_params[:password])
       if @user.save
           redirect_to @user
       else
           render 'new'
       end
    end

    def show
        @user = User.find(params[:id])
        @upcoming_events = @user.attended_events.upcoming
        @past_events = @user.attended_events.past
    end

    private
        def user_params
            params.require(:user).permit(:username, :password)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def signin(user)
        cookies.permanent.signed[:user_id] = user.id
    end

    def current_user
        if (user_id = cookies.signed[:user_id])
            @current_user ||= User.find(user_id)
        else
            @current_user = nil
        end
    end

    def signed_in?
        !current_user.nil?
    end

    def signout
        @current_user = nil
        cookies.delete :user_id
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/index.html.erb
<h1>Events#index</h1>

UPCOMING EVENTS
<br>
<% @upcoming_events.each do |event| %>
    <%= event.description %>
    -- Host: 
    <%= event.host.username %>
    <br>
<% end %>

<br>
PAST EVENTS
<br>
<% @past_events.each do |event| %>
    <%= event.description %>
    -- Host: 
    <%= event.host.username %>
    <br>
<% end %>

app/views/events/new.html.erb
<h1>Create New Event</h1>

<%= form_for @event do |f| %>
    <%= f.label :description %>
    <%= f.text_field :description %>
    <%= f.submit "Create Event" %>
<% end %>

app/views/events/show.html.erb
<h1>Events#show</h1>

Host: 
<%= @event.host.username %>
<br>
<br>
Guest List:
<br>
<% @attendees.each do |attendee| %>
    <%= attendee.username %>
<% end %>

<% if signed_in? && current_user.id == @event.host.id %>
    link_to "invite new guest", new_invitation_path
    then, at invitation have radio buttons with each of current_user's current hosted parties
    and checkboxes for each username
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Private Events</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= link_to "Events", events_path %>
  </head>

  <body>
    <% if signed_in? %>
        <%= link_to "Create Event", new_event_path %>
        Signed in as: 
        <%= link_to "#{current_user.username}", current_user %>
    <% end %>
    
    <% flash.each do |message| %>
          <%= message %>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1> Sign up </h1>

<%= form_for @user do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username %>
    <br>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= f.submit "Sign up!" %>
<% end %>

app/views/users/show.html.erb
<h1>My Hosting Events</h1>

<% @user.hosting_events.each do |event| %>
    <%= link_to "#{event.description}", event %>
<% end %>

<h1>My Events</h1>

UPCOMING EVENTS
<br>
<% @upcoming_events.each do |event| %>
    <%= event.description %>
    <br>
<% end %>
<br>
PAST EVENTS
<br>
<% @past_events.each do |event| %>
    <%= event.description %>
    <br>
<% end %>